### ISSUE TITLE
Problem importing gribapi

### ISSUE THREAD

**Issue by MarkJ1971** [SciTools/conda-recipes-scitools#205]
Hi
I am having trouble using ecmwf_grib on Anaconda. I get this error

`ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory
`

I don't know that much about Anaconda, conda or the ECMWF GRIB_API so apologies if I am doing something wrong...

**Full details**
I am using Anaconda Python 2.7.12, Linux Centos 64-bit, installed Anaconda as user and put it on the path (if that's relevant). 

I installed ecmwf_grib 1.16.0 from SciTools. Conda output is shown in the attachment.

And when I tried to run this code (all it does is import gribapi)

``` python
import sys
import os

#path=os.path.abspath('/home/martin/markj/gribapi_python/')
#if not path in sys.path:
#    sys.path.insert(1, path)
#del path

from gribapi import *
```

I got this error

``` python
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> 
=============== RESTART: /home/martin/markj/JustImportGRIB.py ===============

Traceback (most recent call last):
  File "/home/martin/markj/JustImportGRIB.py", line 9, in <module>
    from gribapi import *
  File "/home/martin/anaconda2again/lib/python2.7/site-packages/gribapi/__init__.py", line 31, in <module>
    import gribapi_swig as _internal
  File "/home/martin/anaconda2again/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 25, in <module>
    _gribapi_swig = swig_import_helper()
  File "/home/martin/anaconda2again/lib/python2.7/site-packages/gribapi/gribapi_swig.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gribapi_swig', fp, pathname, description)
ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory
```

Google found [this](https://github.com/conda-forge/pygrib-feedstock/issues/11) issue report from conda-forge ecmwf_grib but I am not completely sure it is relevant nor am I sure how to apply the suggested workaround.

It seems to me it may be an issue in the ecmwf_grib package. Apologies in advance if I have the wrong end of the stick somehow!

Mark J
[installing.txt](https://github.com/SciTools/conda-recipes-scitools/files/516556/installing.txt)

**Comment by dkillick** [comment]
Hi @MarkJ1971, thanks for raising this issue and providing that text file of the install. I tried running the same command as you in a fresh conda env and could not replicate the problem you are experiencing. I did, however, get a very different set of packages to be installed from what you did:

```
The following NEW packages will be INSTALLED:

    ecmwf_grib: 1.16.0-np110py27_0 scitools
    jasper:     1.900.1-5          scitools
    jpeg:       8d-2               defaults
    mkl:        11.3.3-0           defaults
    numpy:      1.10.4-py27_2      defaults
    six:        1.10.0-py27_0      defaults
```

Note that my package list includes both `jpeg` (the missing SO that's causing your issue) and `jasper` (which pulls in `jpeg`). Neither of these packages show up in your install log, which is a bit odd, and probably points to the source of your issue. This might be happening because one or both of these packages are already installed in your env, and maybe aren't being linked to ecmwf-grib properly.

To try and fix this, could you add to this issue the result of calling `conda list` on the env into which you installed `ecmwf-grib` please? Can you also try creating a new conda env using the `conda create` command and try re-running the ecmwf-grib install command within that env?

**Comment by MarkJ1971** [comment]
Thanks very much @dkillick for having a look at this. 

I looked back at my original notes and I think I left out some details in my initial issue report above (sorry about that). It seems I tried installing from Conda-forge first before I tried SciTools. Maybe that has something to do with it. 

Below is the output from "conda list" right now. Again looking at my notes it seems I have done some more tweaking since I did the steps in the issue report though. I hope I am not wasting your time here...

```
[martin@bonnie Desktop]$ ls
[martin@bonnie Desktop]$ cd /home/martin/anaconda2again/
[martin@bonnie anaconda2again]$ which conda
~/anaconda2again/bin/conda
[martin@bonnie anaconda2again]$ cd ..
[martin@bonnie ~]$ conda list
# packages in environment at /home/martin/anaconda2again:
#
Using Anaconda API: https://api.anaconda.org
_license                  1.1                      py27_1  
_nb_ext_conf              0.3.0                    py27_0  
alabaster                 0.7.9                    py27_0  
anaconda-clean            1.0.0                    py27_0  
anaconda-client           1.5.1                    py27_0  
anaconda                  custom                   py27_0  
anaconda-navigator        1.2.3                    py27_0  
argcomplete               1.0.0                    py27_1  
astroid                   1.4.7                    py27_0  
astropy                   1.1.2               np110py27_0  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports_abc             0.4                      py27_0  
beautifulsoup4            4.5.1                    py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.2                   py27_0  
boto                      2.42.0                   py27_0  
bottleneck                1.0.0               np110py27_1  
cdecimal                  2.3                      py27_2  
cffi                      1.7.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.6                      py27_0  
cloudpickle               0.2.1                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda-build               2.0.2                    py27_0  
cairo                     1.12.18                       8    conda-forge
conda                     4.1.11                   py27_1    conda-forge
conda-env                 2.5.2                    py27_0    conda-forge
fontconfig                2.11.1                        3    conda-forge
freetype                  2.6.3                         1    conda-forge
hdf4                      4.2.12                        0    conda-forge
icu                       56.1                          4    conda-forge
jasper                    1.900.1                       3    conda-forge
jpeg                      9b                            0    conda-forge
libiconv                  1.14                          3    conda-forge
libpng                    1.6.24                        0    conda-forge
libtiff                   4.0.6                         6    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxml2                   2.9.4                         2    conda-forge
matplotlib                1.5.3               np110py27_2    conda-forge
pango                     1.40.1                        0    conda-forge
pillow                    3.4.1                    py27_0    conda-forge
pygrib                    2.0.1                    py27_3    conda-forge
pyproj                    1.9.5.1                  py27_0    conda-forge
qt                        4.8.7                         1    conda-forge
six                       1.10.0                   py27_0    conda-forge
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.3                    py27_0  
cryptography              1.5                      py27_0  
curl                      7.45.0                        0  
cycler                    0.10.0                   py27_0  
cython                    0.24.1                   py27_0  
cytoolz                   0.8.0                    py27_0  
dask                      0.11.0                   py27_0  
datashape                 0.5.2                    py27_0  
dbus                      1.10.10                       0  
decorator                 4.0.10                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.12                     py27_2  
dynd-python               0.7.2                    py27_0  
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py27_1  
filelock                  2.0.6                    py27_0  
flask                     0.11.1                   py27_0  
flask-cors                2.1.2                    py27_0  
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.1.2                    py27_0  
glib                      2.43.0                        1  
greenlet                  0.4.10                   py27_0  
grin                      1.2.1                    py27_3  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.6.0               np110py27_0  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.15.1                      3  
heapdict                  1.0.0                    py27_1  
idna                      2.1                      py27_0  
imagesize                 0.7.1                    py27_0  
ipaddress                 1.0.16                   py27_0  
ipykernel                 4.5.0                    py27_0  
ipython                   5.1.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.2                      py27_1  
jedi                      0.9.0                    py27_1  
jinja2                    2.8                      py27_1  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_core              4.2.0                    py27_0  
lazy-object-proxy         1.2.1                    py27_0  
libdynd                   0.7.2                         0  
libffi                    3.2.1                         0  
libgcc                    4.8.5                         2  
libgfortran               3.0.0                         1  
libnetcdf                 4.3.3.1                       3  
libsodium                 1.0.10                        0  
libxcb                    1.12                          0  
libxslt                   1.1.28                        0  
llvmlite                  0.11.0                   py27_0  
locket                    0.2.0                    py27_1  
lxml                      3.6.4                    py27_0  
markupsafe                0.23                     py27_2  
mistune                   0.7.3                    py27_0  
mkl                       11.3.3                        0  
mkl-service               1.1.2                    py27_2  
mpmath                    0.19                     py27_1  
multipledispatch          0.4.8                    py27_0  
nb_anacondacloud          1.2.0                    py27_0  
nb_conda                  2.0.0                    py27_0  
nb_conda_kernels          2.0.0                    py27_0  
nbconvert                 4.2.0                    py27_0  
nbformat                  4.1.0                    py27_0  
nbpresent                 3.0.2                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.1                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.2.3                    py27_0  
numba                     0.26.0              np110py27_0  
numexpr                   2.5.2               np110py27_1  
numpy                     1.10.4                   py27_2  
odo                       0.5.0                    py27_1  
openpyxl                  2.3.2                    py27_0  
openssl                   1.0.2j                        0  
pandas                    0.18.1              np110py27_0  
partd                     0.3.6                    py27_0  
patchelf                  0.9                           0  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pip                       8.1.2                    py27_0  
pixman                    0.32.6                        0  
pkginfo                   1.3.2                    py27_0  
ply                       3.9                      py27_0  
prompt_toolkit            1.0.3                    py27_0  
psutil                    4.3.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.31                   py27_0  
pyasn1                    0.1.9                    py27_0  
pycairo                   1.10.0                   py27_0  
pycosat                   0.6.1                    py27_1  
pycparser                 2.14                     py27_1  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.19.5.3                 py27_0  
pyflakes                  1.3.0                    py27_0  
pygments                  2.1.3                    py27_0  
pylint                    1.5.4                    py27_1  
pyopenssl                 16.0.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_3  
pytables                  3.2.2               np110py27_1  
pytest                    2.9.2                    py27_0  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.6.1                 py27_0  
pyyaml                    3.12                     py27_0  
pyzmq                     15.4.0                   py27_0  
qtawesome                 0.3.3                    py27_0  
qtconsole                 4.2.1                    py27_0  
qtpy                      1.1.2                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
requests                  2.11.1                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_0  
scikit-image              0.12.3              np110py27_1  
scikit-learn              0.17.1              np110py27_2  
scipy                     0.17.1              np110py27_1  
ecmwf_grib                1.16.0              np110py27_0    scitools
setuptools                27.2.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.4.6                    py27_0  
spyder                    2.3.9                    py27_1  
sqlalchemy                1.0.13                   py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.6.1               np110py27_1  
sympy                     1.0                      py27_0  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.0                    py27_0  
tornado                   4.4.1                    py27_0  
traitlets                 4.3.0                    py27_0  
unicodecsv                0.14.1                   py27_0  
wcwidth                   0.1.7                    py27_0  
werkzeug                  0.11.11                  py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
wrapt                     1.10.6                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.3                    py27_0  
xlwt                      1.1.2                    py27_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  
[martin@bonnie ~]$ 

```

**Comment by ajdawson** [comment]
I suspect this is a dependency conflict, since you have ecmwf_grib from the scitools channel but libjpeg from the conda-forge channel. Some packages are quite sensitive to dependencies, and whilst the combination you have may appear to satisfy the scitools ecmwf_grib package requirements, in actual fact something is broken. My suggestion would be to try packages from the same channel (grib and jpeg) and see if that resolves your issue.

**Comment by pelson** [comment]
Closed due to the deprecation of this repo. #250
