### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by marqh** [SciTools/conda-recipes-scitools#219]
all uploads to anaconda.org are failing at present, see
https://circleci.com/gh/SciTools/conda-recipes-scitools/495
https://travis-ci.org/SciTools/conda-recipes-scitools/builds/183896731

with
```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build-all", line 11, in <module>
    load_entry_point('conda-build-all==1.0.0', 'console_scripts', 'conda-build-all')()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/cli.py", line 90, in main
    b.main()
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 265, in main
    config=build_config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/builder.py", line 285, in post_build
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/artefact_destination.py", line 118, in make_available
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build_all/build.py", line 42, in upload
    fname = bldpkg_path(meta, config)
TypeError: bldpkg_path() takes 1 positional argument but 2 were given
```

we need to find out why this is happening and fix it

it seems to be stuck in conda-build-all, which may to be pinned to version 1.0.0, although the docker script
https://github.com/SciTools/conda-recipes-scitools/blob/master/scripts/run_docker_build.sh#L45
just seems to grab whatever is on conda-forge and conda-build-all has been at 1.0.0 for more than 3 months
https://anaconda.org/conda-forge/conda-build-all/files

puzzling

**Comment by ocefpaf** [comment]
@marqh PR https://github.com/SciTools/conda-build-all/pull/68#issuecomment-267606883 fixed this but we need a new `conda-build-all` release.

Meanwhile you can try to pin to other `conda-build` version. See https://github.com/astropy/conda-channel-astropy/issues/105#issuecomment-265346930

**Comment by marqh** [comment]
a new conda-build-all release did not fix this I'm afraid, i'm trying pinning conda-build instead
 #220

**Comment by pelson** [comment]
Closed due to the deprecation of this repo. #250
